#!/usr/bin/env bash

# Halt when error occurs
set -e

# Set green and no-color
C='\033[0;32m'
NC='\033[0m'

echo -e "${C}Setting everything up...${NC}"

# Install zsh
sudo apt-get -y install zsh

# Install oh-my-zsh if not present
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

# Change default shell to zsh
chsh -s /bin/zsh

# Install fd if not present
STATUS=$(dpkg-query -W -f='${Status}' fd-musl | grep "install ok installed")

if [ "" == "$STATUS" ]; then
  TEMP_DEB="$(mktemp)" &&
  wget -O "$TEMP_DEB" 'https://github.com/sharkdp/fd/releases/download/v7.1.0/fd-musl_7.1.0_amd64.deb' &&
  sudo dpkg -i "$TEMP_DEB"
  rm -f "$TEMP_DEB"
fi

# Install silversearcher-ag
sudo apt-get -y install silversearcher-ag

# Create symlinks
ln -sf "$(pwd)/tmux/.tmux.conf" ~
ln -sf "$(pwd)/vim/.vimrc" ~
ln -sf "$(pwd)/git/.gitconfig" ~
ln -sf "$(pwd)/zsh/.zshrc" ~
ln -sf "$(pwd)/zsh/.aliases" ~
ln -sf "$(pwd)/zsh/.init" ~

echo -e "${C}Done!"
echo "Don't forget to re-login to reflect all changes."
echo -e "You might need to PlugInstall and source as well!${NC}"
