#!/usr/bin/env bash

# Halt when error occurs
set -e

# Set green and no-color
C='\033[0;32m'
NC='\033[0m'

echo -e "${C}Setting everything up...${NC}"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Install zsh
  sudo apt-get -y install zsh

  # Install fd
  TEMP_DEB="$(mktemp)" &&
  wget -O "$TEMP_DEB" 'https://github.com/sharkdp/fd/releases/download/v7.1.0/fd-musl_7.1.0_amd64.deb' &&
  sudo dpkg -i "$TEMP_DEB"
  rm -f "$TEMP_DEB"

  # Install silversearcher-ag
  sudo apt-get -y install silversearcher-ag

  # Install universal-ctags
  if [ ! -d "$HOME/.ctags" ]; then
    git clone https://github.com/universal-ctags/ctags.git ~/.ctags &&
    ~/.ctags/autogen.sh &&
    ~/.ctags/configure &&
    make -C ~/.ctags &&
    make install -C ~/.ctags
  fi
elif [[ "$OSTYPE" == "darwin"*  ]]; then
  # Install zsh
  brew install zsh

  # Install fd
  brew install fd

  # Install silversearcher-ag
  brew install the_silver_searcher

  # Install ctags
  brew install ctags
fi

# Install oh-my-zsh if not present
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

# Change default shell to zsh
chsh -s /bin/zsh

# Create symlinks
ln -sf "$(pwd)/tmux/.tmux.conf" ~
ln -sf "$(pwd)/vim/.vimrc" ~
ln -sf "$(pwd)/git/.gitconfig" ~
ln -sf "$(pwd)/git/.gitignore_global" ~
ln -sf "$(pwd)/zsh/.zshrc" ~
ln -sf "$(pwd)/zsh/.aliases" ~
ln -sf "$(pwd)/zsh/.init" ~

echo -e "${C}Done!"
echo "Don't forget to re-login to reflect all changes."
echo "You might need to source and PlugInstall as well."
echo "To use intended colors, change the terminal's text color to #ABB2BF and background color to #262626."
echo -e "P.S. Generate ctags for individual projects${NC}"
