#!/usr/bin/env bash

# Halt when error occurs
set -e

# Set green and no-color
C='\033[0;32m'
NC='\033[0m'

echo -e "${C}Removing everything...${NC}"

# Remove fd
sudo dpkg --purge fd-musl

# Remove silversearcher-ag
sudo apt-get -y remove silversearcher-ag

# Remove universal-ctags
if [ -d "$HOME/.ctags" ]; then
  # Apparently, this command is not a thing.
  # Maybe nuking the directory is enough?
  #
  # make uninstall -C ~/.ctags
  rm ~/.ctags -rf
fi

# Delete symlinks
rm ~/.tmux.conf -f
rm ~/.vimrc -f
rm ~/.gitconfig -f
rm ~/.gitignore_global -f
rm ~/.zshrc -f
rm ~/.aliases -f
rm ~/.init -f

# Remove vim plugins
rm ~/.vim -rf

# Remove oh-my-zsh if present
if [ -d "$HOME/.oh-my-zsh" ]; then
  rm ~/.oh-my-zsh -rf
fi

# Change default shell to bash
chsh -s /bin/bash

# Remove zsh
sudo apt-get -y remove zsh

echo -e "${C}Done!"
echo "Don't forget to re-login to reflect all changes."
echo -e "P.S. Remove ctags under affected projects${NC}"
