#!/usr/bin/env bash

# Halt when error occurs
set -e

# Set green and no-color
C='\033[0;32m'
NC='\033[0m'

echo -e "${C}Removing everything...${NC}"

# Change default shell to bash
if [ "$SHELL" != "/bin/bash" ]; then
  chsh -s /bin/bash
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Remove zsh
  sudo apt-get -y remove zsh

  # Remove fd
  sudo dpkg --purge fd-musl

  # Remove silversearcher-ag
  sudo apt-get -y remove silversearcher-ag

  # Remove universal-ctags
  if [ -d "$HOME/.ctags" ]; then
    # Apparently, this command is not a thing.
    # Maybe nuking the directory is enough?
    #
    # make uninstall -C ~/.ctags
    rm -rf ~/.ctags
  fi
elif [[ "$OSTYPE" == "darwin"*  ]]; then
  if type "zsh" > /dev/null; then
    brew uninstall zsh
  fi

  if type "fd" > /dev/null; then
    brew uninstall fd
  fi

  if type "ag" > /dev/null; then
    brew uninstall the_silver_searcher
  fi

  if type "ctags" > /dev/null; then
    brew uninstall ctags
  fi
fi

# Remove oh-my-zsh if present
if [ -d "$HOME/.oh-my-zsh" ]; then
  rm ~/.oh-my-zsh -rf
fi

# Delete symlinks
rm -f ~/.tmux.conf
rm -f ~/.vimrc
rm -f ~/.gitconfig
rm -f ~/.gitignore_global
rm -f ~/.zshrc
rm -f ~/.aliases
rm -f ~/.init

# Remove vim plugins
rm -rf ~/.vim

# Remove fzf
rm -f ~/.fzf.bash
rm -f ~/.fzf.zsh
rm -rf ~/.fzf

echo -e "${C}Done!"
echo "Don't forget to re-login to reflect all changes."
echo -e "P.S. Remove ctags under affected projects${NC}"
